### ISSUE TITLE
is it possible to...

### ISSUE THREAD

**Issue by borjita2019** [Mr-Blahaj/WhatsApp-Discord-Link#1]
is it possible to add a voice channel thing where the current whatsapp voice call links with the discord voice channel? (something like a slash command /call that joins the voice channel that the user is in and bridges the whatsapp voice call with the discord voice channel)

**Comment by arnav-khanna** [comment]
It could be possible but it surely won't be easy. However I do not recommend it as the call on WhatsApp will be transferred to Discord after which your response will again be transferred to WhatsApp, so there is a chance of that there will be a delay of 2-3 seconds between the question and the response. I can try experimenting and doing some stuff when I am free! Thats a nice suggestion tho

**Comment by borjita2019** [comment]
dont care about the delay, even if its 1 year of delay, I HAVE BEEN LOOKING FOR THAT SINCE 1 YEAR.

**Comment by arnav-khanna** [comment]
it will be difficult, and I don't think whatsapp-web.js can be used to transmit calls, so it also requires custom infrastructure. I can think about doing it when I am free

**Comment by borjita2019** [comment]
thanks anyways, appreciate your hard work

**Comment by arnav-khanna** [comment]
Thank you! Have a good day 😄 
You can contact me through Discord if you want, My Username is !Mr.Blahaj#7518
